FROM afchi:dev
ENV DEBIAN_FRONTEND noninteractive
ARG PYTHON_VERSION=3.8


RUN apt-get install -y libsndfile1 &&\
    apt-get clean &&\
    git clone https://github.com/Afchis/configs.git ~/Downloads/configs &&\
    cd ~/Downloads/configs &&\
    pip --no-cache-dir install -r requirements.txt &&\
    rm -rf ~/Downloads/configs


TAG afchi:debug

