FROM nvidia/cuda:11.5.0-base-ubuntu20.04
ENV DEBIAN_FRONTEND noninteractive
ARG PYTHON_VERSION=3.8


### install python3.8
RUN apt-get update &&\
    apt-get install -y python3.8\
		       python3-pip &&\
    apt-get clean &&\
    ln -s /usr/bin/python3.8 /usr/local/bin/python &&\
    ln -s /usr/bin/python3.8 /usr/local/bin/python3

