FROM afchi:dev
ENV DEBIAN_FRONTEND noninteractive
ARG PYTHON_VERSION=3.8


RUN apt-get install -y libsndfile1 &&\
    git clone https://github.com/Afchis/configs.git ~/Downloads/configs &&\
    cd ~/Downloads/configs &&\
    pip install -r requirements.txt

